---
- name  : "Node Exporter Setup"
  hosts : combined
  become: yes
  tasks :
    - name: "Download the Monitoring Repo"
      shell: git clone https://github.com/Pinakastra-Computing/Monitoring.git /opt/pinakastra/monitoring

    - name: "Change the working directory to /opt/pinakastra/monitoring"
      shell: /bin/bash node.sh
      args:
        chdir: /opt/pinakastra/monitoring

    - name: "Remove the Monitoring Repo"
      shell: rm -rf /opt/pinakastra/monitoring